#@ load("@ytt:data", "data")

#@ def pipeline_image():
#@   return data.values.docker_registry + "/galoy-infra-pipeline"
#@ end

jobs:
- name: build-pipeline-image
  serial: true
  plan:
  - {get: pipeline-image-def, trigger: true}
  - task: build
    privileged: true
    config:
      platform: linux
      image_resource:
        type: registry-image
        source:
          repository: vito/oci-build-task
      inputs:
      - name: pipeline-image-def
      outputs:
      - name: image
      params:
        CONTEXT: pipeline-image-def/ci/image
      run:
        path: build
  - put: pipeline-image
    params:
      image: image/image.tar

- name: bootstrap
  serial_groups: [testflight]
  plan:
  - put: testflight-lock
    params: { claim: gcp-testflight }
  - in_parallel:
    - { get: src, trigger: true }
    - { get: pipeline-tasks }
- name: cleanup
  serial_groups: [testflight]
  plan:
  - in_parallel:
    - { get: testflight-lock, passed: [bootstrap]}
    - { get: src, passed: [bootstrap], trigger: true }
  - put: testflight-lock
    params: { release: testflight-lock }

        #! - name: inception
        #!   serial_groups: [testflight]
        #!   plan:
        #!   - in_parallel:
        #!     - { get: src, passed: [bootstrap], trigger: true }
        #!     - { get: pipeline-tasks }
        #!     - { get: gcp-testflight, passed: [bootstrap] }
        #!   - put: gcp-testflight
        #!     resource: testflight-lock
        #!     params: { release: gcp-testflight }

resources:
- name: src
  type: git
  source:
    ignore_paths: ["ci/*[^md]"]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
- name: pipeline-tasks
  type: git
  source:
    paths: [ci/tasks/*, Makefile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: pipeline-image
  type: registry-image
  source:
    tag: latest
    username: #@ data.values.docker_registry_user
    password: #@ data.values.docker_registry_password
    repository: #@ pipeline_image()
- name: pipeline-image-def
  type: git
  source:
    paths: [ci/image/Dockerfile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: testflight-lock
  type: pool
  source:
    uri: git@github.com:GaloyMoney/concourse-locks.git
    branch: main
    pool: infra-testflight
    private_key: #@ data.values.github_private_key
