#@ load("@ytt:data", "data")

#@ def pipeline_image():
#@   return data.values.docker_registry + "/galoy-deployments-pipeline"
#@ end

#@ def task_image_config():
type: registry-image
source:
  username: #@ data.values.docker_registry_user
  password: #@ data.values.docker_registry_password
  repository: #@ pipeline_image()
#@ end

#@ def testflight_task_params():
GOOGLE_CREDENTIALS: #@ data.values.testflight_gcp_creds
SSH_PRIVATE_KEY: #@ data.values.testflight_ssh_private_key
SSH_PUB_KEY: #@ data.values.testflight_ssh_pub_key
TESTFLIGHT_ADMINS: #@ data.values.testflight_admins
KUBE_HOST: #@ data.values.concourse_tf_kube_host
KUBE_CA_CERT: #@ data.values.concourse_tf_kube_ca_cert
KUBE_TOKEN: #@ data.values.concourse_tf_kube_token
TF_VAR_name_prefix: testflight-b
TF_VAR_gcp_project: galoy-infra-testflight
TF_VAR_enable_services: false
BRANCH: #@ data.values.git_branch
#@ end

groups:
- name: all
  jobs:
  - testflight-bootstrap
  - testflight-inception
  - testflight-platform
  - testflight-cleanup
  - bump-repos
  - staging-inception
  - staging-platform
  - staging-services
- name: testflight
  jobs:
  - testflight-bootstrap
  - testflight-inception
  - testflight-platform
  - testflight-cleanup
  - bump-repos
- name: staging
  jobs:
  - staging-inception
  - staging-platform
  - staging-services

jobs:
- name: testflight-bootstrap
  serial_groups: [testflight]
  plan:
  - in_parallel:
    - { get: modules, trigger: true}
    - { get: repo }
    - { get: pipeline-tasks }
  - task: bootstrap
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: modules
      params: #@ testflight_task_params()
      run:
        path: pipeline-tasks/ci/tasks/bootstrap.sh

- name: testflight-inception
  serial_groups: [testflight]
  plan:
  - in_parallel:
    - { get: modules, trigger: true, passed: [testflight-bootstrap]}
    - { get: repo, trigger: true, passed: [testflight-bootstrap] }
    - { get: pipeline-tasks }
  - task: inception
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: modules
      params: #@ testflight_task_params()
      run:
        path: pipeline-tasks/ci/tasks/inception.sh

- name: testflight-platform
  serial_groups: [testflight]
  plan:
  - in_parallel:
    - { get: modules, trigger: true, passed: [testflight-inception]}
    - { get: repo, trigger: true, passed: [testflight-inception] }
    - { get: pipeline-tasks }
  - task: platform
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: modules
      params: #@ testflight_task_params()
      run:
        path: pipeline-tasks/ci/tasks/platform.sh

- name: testflight-cleanup
  serial_groups: [testflight]
  plan:
  - in_parallel:
    - { get: modules, passed: [testflight-platform], trigger: true}
    - { get: repo, trigger: true, passed: [testflight-platform] }
    - { get: pipeline-tasks }
  - task: teardown
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: pipeline-tasks
      - name: repo
      - name: modules
      outputs: 
      - name: repo
      params: #@ testflight_task_params()
      run:
        path: pipeline-tasks/ci/tasks/teardown.sh

- name: bump-repos
  plan:
  - in_parallel:
    - { get: galoy-staging }
    - { get: modules, passed: [testflight-cleanup], trigger: true}
    - { get: repo, trigger: true, passed: [testflight-cleanup] }
    - { get: pipeline-tasks }
  - task: bump-repos
    config:
      platform: linux
      image_resource: #@ task_image_config()
      inputs:
      - name: galoy-staging
      - name: pipeline-tasks
      - name: modules
      - name: repo
      outputs:
      - name: repo
      - name: galoy-staging
      params:
        BRANCH: #@ data.values.git_branch
      run:
        path: pipeline-tasks/ci/tasks/bump-repos.sh
  - in_parallel:
    - put: repo
      params:
        repository: repo
        rebase: true
    - put: galoy-staging
      params:
        repository: galoy-staging
        rebase: true


- name: staging-inception
  serial_groups: [staging]
  plan:
  - in_parallel:
    - { get: cepler-galoy-staging, trigger: true }
  - put: tf-staging-inception
    params:
      terraform_source: cepler-galoy-staging/gcp/staging/inception

- name: staging-platform
  serial_groups: [staging]
  plan:
  - in_parallel:
    - { get: cepler-galoy-staging, trigger: true, passed: [staging-inception] }
  - put: tf-staging-platform
    params:
      terraform_source: cepler-galoy-staging/gcp/staging/platform

- name: staging-services
  serial_groups: [staging]
  plan:
  - in_parallel:
    - { get: cepler-galoy-staging, trigger: true, passed: [staging-platform] }
  - put: tf-staging-services
    tags: ["staging"]
    params:
      terraform_source: cepler-galoy-staging/gcp/staging/services
  - put: cepler-out
    params: { repository: cepler-galoy-staging }

resources:
- name: repo
  type: git
  source:
    ignore_paths: ["ci/*[^md]"]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
- name: modules
  type: git
  source:
    paths: ["modules"]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
- name: pipeline-tasks
  type: git
  source:
    paths: [ci/tasks/*, Makefile]
    uri: #@ data.values.git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
- name: galoy-staging
  type: git
  source:
    uri: #@ data.values.deployments_git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key

- name: tf-staging-inception
  type: terraform
  source:
    env_name: default
    backend_type: gcs
    backend_config:
      bucket: #@ data.values.staging_state_bucket
      prefix: galoy-staging/inception
      credentials: #@ data.values.staging_inception_creds
    env:
      GOOGLE_CREDENTIALS: #@ data.values.staging_inception_creds

- name: tf-staging-platform
  type: terraform
  source:
    env_name: default
    backend_type: gcs
    backend_config:
      bucket: #@ data.values.staging_state_bucket
      prefix: galoy-staging/platform
      credentials: #@ data.values.staging_inception_creds
    env:
      GOOGLE_CREDENTIALS: #@ data.values.staging_inception_creds

- name: tf-staging-services
  type: terraform
  source:
    env_name: default
    backend_type: gcs
    backend_config:
      bucket: #@ data.values.staging_state_bucket
      prefix: galoy-staging/services/base
      credentials: #@ data.values.staging_inception_creds
    env:
      GOOGLE_CREDENTIALS: #@ data.values.staging_inception_creds

- name: cepler-out
  type: cepler-out
  source:
    uri: #@ data.values.deployments_git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
    environment: gcp-staging
    config: cepler/infra.yml
    gates_branch: #@ data.values.cepler_gates_branch
    gates_file: #@ data.values.cepler_gates_file

- name: cepler-galoy-staging
  type: cepler-in
  source:
    uri: #@ data.values.deployments_git_uri
    branch: #@ data.values.git_branch
    private_key: #@ data.values.github_private_key
    environment: gcp-staging
    config: cepler/infra.yml
    gates_branch: #@ data.values.cepler_gates_branch
    gates_file: #@ data.values.cepler_gates_file

resource_types:
- name: terraform
  type: docker-image
  source:
    repository: ljfranklin/terraform-resource
    tag: latest

- name: cepler-in
  type: registry-image
  source:
    repository: cepler/cepler-concourse-resource
    tag: latest

- name: cepler-out
  type: registry-image
  source:
    repository: cepler/cepler-concourse-resource
    tag: latest
